# Netflix Data Cleaning

In [1]:
#Read data with pandas
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("netflix.csv")

In [3]:
data.isnull().sum()

title                  0
rating                 0
ratingdescription     59
rating_level           0
release_year           0
user_rating_score    395
user_rating_size       0
dtype: int64

In [4]:
data[data["ratingdescription"].isnull()]

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
25,Marvel's Iron Fist,TV-MA,NaN,110,2017,98.0,80
31,OperaÃ§Ãµes Especiais,TV-MA,NaN,110,2015,NaN,82
39,Girlboss,TV-MA,NaN,110,2017,94.0,80
42,Sand Castle,TV-MA,NaN,110,2017,89.0,80
44,Sandy Wexler,TV-14,NaN,90,2017,92.0,80
45,O Amor no DivÃ£,TV-MA,NaN,110,2016,NaN,82
46,Stronger Than the World,NR,NaN,124,2016,NaN,82
48,Happily Married,TV-14,NaN,90,2015,NaN,82
49,Pandora,TV-MA,NaN,110,2016,NaN,82
77,Marvel's Iron Fist,TV-MA,NaN,110,2017,98.0,80
85,Ingobernable,TV-MA,NaN,110,2017,96.0,80
93,Girlboss,TV-MA,NaN,110,2017,94.0,80
94,The Discovery,TV-MA,NaN,110,2017,NaN,82
95,Sand Castle,TV-MA,NaN,110,2017,89.0,80
96,Sandy Wexler,TV-14,NaN,90,2017,92.0,80
98,Cheer Squad,TV-PG,NaN,70,2016,61.0,80
99,Only for One Night,TV-MA,NaN,110,2016,78.0,80
118,Marvel's Iron Fist,TV-MA,NaN,110,2017,98.0,80
129,Abstract: The Art of Design,TV-14,NaN,90,2017,NaN,82
137,Minimalism: A Documentary About the Important ...,TV-PG,NaN,70,2016,NaN,82
138,Girlboss,TV-MA,NaN,110,2017,94.0,80
139,Hot Girls Wanted: Turned On,TV-MA,NaN,110,2017,NaN,82
140,The Discovery,TV-MA,NaN,110,2017,NaN,82
142,Sandy Wexler,TV-14,NaN,90,2017,92.0,80
144,Win It All,TV-MA,NaN,110,2017,NaN,82
146,Amy Schumer: The Leather Special,TV-MA,NaN,110,2017,NaN,82
147,Louis C.K. 2017,TV-MA,NaN,110,2017,71.0,80
181,Skins,TV-MA,NaN,110,2017,NaN,82
186,Deidra & Laney Rob a Train,TV-14,NaN,90,2017,NaN,82
187,Girlboss,TV-MA,NaN,110,2017,94.0,80
188,Hot Girls Wanted: Turned On,TV-MA,NaN,110,2017,NaN,82
190,Hurricane Bianca,TV-MA,NaN,110,2016,NaN,82
193,Lazy Eye,TV-MA,NaN,110,2016,NaN,82
194,Like Cotton Twines,NR,NaN,124,2016,NaN,82
195,The Wedding Party,TV-14,NaN,90,2016,NaN,82
197,Only for One Night,TV-MA,NaN,110,2016,78.0,80
198,Boy Bye,TV-MA,NaN,110,2016,NaN,82
230,Abstract: The Art of Design,TV-14,NaN,90,2017,NaN,82
240,Hot Girls Wanted: Turned On,TV-MA,NaN,110,2017,NaN,82
242,Better Off Single,TV-MA,NaN,110,2016,NaN,82
243,Sandy Wexler,TV-14,NaN,90,2017,92.0,80
246,Tramps,TV-MA,NaN,110,2017,NaN,82
247,Slam,TV-MA,NaN,110,2017,NaN,82
248,Cheer Squad,TV-PG,NaN,70,2016,61.0,80
297,Amy Schumer: The Leather Special,TV-MA,NaN,110,2017,NaN,82
298,Cheer Squad,TV-PG,NaN,70,2016,61.0,80
346,Girlboss,TV-MA,NaN,110,2017,94.0,80
348,Felipe Neto: My Life Makes No Sense,TV-MA,NaN,110,2017,NaN,82
349,Cheer Squad,TV-PG,NaN,70,2016,61.0,80
394,Ingobernable,TV-MA,NaN,110,2017,96.0,80
395,Girlboss,TV-MA,NaN,110,2017,94.0,80
433,Marvel's Iron Fist,TV-MA,NaN,110,2017,98.0,80
442,Hap and Leonard,TV-MA,NaN,110,2016,57.0,80
448,I.T,NR,NaN,124,2016,NaN,82
496,Girlboss,TV-MA,NaN,110,2017,94.0,80
599,Growing Up Wild,G,NaN,35,2016,80.0,80
748,Growing Up Wild,G,NaN,35,2016,80.0,80
949,Growing Up Wild,G,NaN,35,2016,80.0,80
999,Growing Up Wild,G,NaN,35,2016,80.0,80

In [5]:
data[data["user_rating_score"].isnull()]

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
14,The Hunter,R,language and brief violence,100,2011,NaN,82
15,Lottie Dottie Chicken,TV-Y,Suitable for all ages.,10,2009,NaN,82
21,"Ã“ Pai, Ã“ - Look at This",TV-MA,For mature audiences. May not be suitable for...,110,2007,NaN,82
22,Nymphomaniac: Volume 1,NR,This movie has not been rated.,124,2013,NaN,82
...,...,...,...,...,...,...,...
993,Wiener Dog Internationals,G,General Audiences. Suitable for all ages.,35,2015,NaN,82
994,Pup Star,G,General Audiences. Suitable for all ages.,35,2016,NaN,82
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82

In [6]:
data.head()

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80

In [7]:
data.tail()

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

In [8]:
data.shape

(1000, 7)

In [9]:
data.sample()

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
137,Minimalism: A Documentary About the Important ...,TV-PG,NaN,70,2016,NaN,82

In [10]:
data.columns

Index(['title', 'rating', 'ratingdescription', 'rating_level', 'release_year',
       'user_rating_score', 'user_rating_size'],
      dtype='object')

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              1000 non-null   object
 1   rating             1000 non-null   object
 2   ratingdescription  941 non-null    object
 3   rating_level       1000 non-null   int64
 4   release_year       1000 non-null   int64
 5   user_rating_score  605 non-null    float64
 6   user_rating_size   1000 non-null   int64
dtypes: float64(1), int64(3), object(3)
memory usage: 54.8+ KB

In [12]:
data.isnull().sum()

title                  0
rating                 0
ratingdescription     59
rating_level           0
release_year           0
user_rating_score    395
user_rating_size       0
dtype: int64

### Loc & ILOC

### Selection based on index by loc

In [13]:
data.loc[(data.rating == "PG-13")]

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
250,The Waterboy,PG-13,language and some crude sexual humor,80,1998,82.0,80
251,10 Things I Hate About You,PG-13,"adult content, adult language and mild violence",80,1999,68.0,80
253,How to Lose a Guy in 10 Days,PG-13,some sex-related material,80,2003,56.0,80
254,The Benchwarmers,PG-13,"crude and suggestive humor, and for language",80,2006,77.0,80
255,Step Up,PG-13,"thematic elements, brief violence and innuendo",80,2006,64.0,80
257,Twilight,PG-13,some violence and one sexual scene,80,2008,89.0,80
273,Mean Girls 2,PG-13,"For some rude and suggestive material, and for...",80,2011,NaN,82
286,Safe Haven,PG-13,thematic material involving threatening behavi...,80,2013,62.0,80
300,The Waterboy,PG-13,language and some crude sexual humor,80,1998,82.0,80
302,The Wedding Planner,PG-13,language and some sexual humor,80,2001,NaN,82
306,Twilight,PG-13,some violence and one sexual scene,80,2008,89.0,80
322,Mean Girls 2,PG-13,"For some rude and suggestive material, and for...",80,2011,NaN,82
335,Trouble with the Curve,PG-13,Parents strongly cautioned. May be inappropria...,80,2012,63.0,80
372,Unconditional,PG-13,some violent content and mature thematic elements,80,2012,NaN,82

In [14]:
data.loc[(data.rating == "PG-13") & (data["release_year"] == 2011)]

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
273,Mean Girls 2,PG-13,"For some rude and suggestive material, and for...",80,2011,NaN,82
322,Mean Girls 2,PG-13,"For some rude and suggestive material, and for...",80,2011,NaN,82

In [15]:

data.loc[(data.rating == "PG-13") | (data["release_year"] == 2011)]

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
14,The Hunter,R,language and brief violence,100,2011,NaN,82
66,One Tree Hill,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,90.0,80
73,Inside Russia's Toughest Prison,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,NaN,82
114,Friends with Benefits,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,NaN,82
213,Friends with Benefits,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,NaN,82
250,The Waterboy,PG-13,language and some crude sexual humor,80,1998,82.0,80
251,10 Things I Hate About You,PG-13,"adult content, adult language and mild violence",80,1999,68.0,80
253,How to Lose a Guy in 10 Days,PG-13,some sex-related material,80,2003,56.0,80
254,The Benchwarmers,PG-13,"crude and suggestive humor, and for language",80,2006,77.0,80
255,Step Up,PG-13,"thematic elements, brief violence and innuendo",80,2006,64.0,80
257,Twilight,PG-13,some violence and one sexual scene,80,2008,89.0,80
273,Mean Girls 2,PG-13,"For some rude and suggestive material, and for...",80,2011,NaN,82
286,Safe Haven,PG-13,thematic material involving threatening behavi...,80,2013,62.0,80
300,The Waterboy,PG-13,language and some crude sexual humor,80,1998,82.0,80
302,The Wedding Planner,PG-13,language and some sexual humor,80,2001,NaN,82
306,Twilight,PG-13,some violence and one sexual scene,80,2008,89.0,80
322,Mean Girls 2,PG-13,"For some rude and suggestive material, and for...",80,2011,NaN,82
324,One Tree Hill,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,90.0,80
335,Trouble with the Curve,PG-13,Parents strongly cautioned. May be inappropria...,80,2012,63.0,80
372,Unconditional,PG-13,some violent content and mature thematic elements,80,2012,NaN,82
475,Forensic Files,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,88.0,80
521,Oscar's Oasis,TV-G,Suitable for all ages.,35,2011,NaN,82
523,The Adventures of Chuck & Friends,TV-Y,Suitable for all ages.,10,2011,NaN,82
569,LEGO Ninjago: Masters of Spinjitzu: Way of the...,TV-Y7-FV,Suitable for children ages 7 and older. Conte...,42,2011,NaN,82
669,DreamWorks Spooky Stories: Volume 2,TV-PG,Parental guidance suggested. May not be suitab...,70,2011,NaN,82
779,A Monster in Paris,PG,"some action violence involving gunplay, and mi...",60,2011,NaN,82
781,DreamWorks How to Train Your Dragon Legends,TV-PG,Parental guidance suggested. May not be suitab...,70,2011,NaN,82
786,PopPixie,TV-G,Suitable for all ages.,35,2011,NaN,82
818,The Little Engine That Could,G,General Audiences. Suitable for all ages.,35,2011,NaN,82
879,A Monster in Paris,PG,"some action violence involving gunplay, and mi...",60,2011,NaN,82
881,DreamWorks How to Train Your Dragon Legends,TV-PG,Parental guidance suggested. May not be suitab...,70,2011,NaN,82
886,PopPixie,TV-G,Suitable for all ages.,35,2011,NaN,82
981,Dolphin Tale,PG,some mild thematic elements,60,2011,NaN,82

In [16]:
data.loc[(data.rating == "TV-14")]

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
7,The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
9,Pretty Little Liars,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80
...,...,...,...,...,...,...,...
489,Rosewood,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2015,81.0,80
491,Quantico,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,88.0,80
492,Limitless,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,84.0,80
495,No Tomorrow,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
499,Greenleaf,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,62.0,80

In [17]:
 data.loc[(data.rating == "TV-14") & (data["user_rating_score"] >= 90 )]

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
7,The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
9,Pretty Little Liars,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80
...,...,...,...,...,...,...,...
472,Person of Interest,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,93.0,80
474,Scandal,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,92.0,80
476,Sherlock,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
477,The Client List,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2013,92.0,80
483,The Blacklist,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80

In [18]:
data.loc[(data.rating == "TV-14")]

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
7,The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
9,Pretty Little Liars,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80
...,...,...,...,...,...,...,...
489,Rosewood,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2015,81.0,80
491,Quantico,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,88.0,80
492,Limitless,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,84.0,80
495,No Tomorrow,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
499,Greenleaf,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,62.0,80

In [19]:
data.loc[(data.rating == "TV-14"),["title", "rating_level"]]

                   title  rating_level
2         Grey's Anatomy            90
3           Prison Break            90
5           Supernatural            90
7    The Vampire Diaries            90
9    Pretty Little Liars            90
..                   ...           ...
489             Rosewood            90
491             Quantico            90
492            Limitless            90
495          No Tomorrow            90
499            Greenleaf            90

[234 rows x 2 columns]

### Selection based on index by iloc

In [20]:
data.iloc[[2,5]]

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80

In [21]:
data.iloc[[2,5],0:2]

            title rating
2  Grey's Anatomy  TV-14
5    Supernatural  TV-14

In [22]:
data.iloc[1:3]

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80

In [23]:
data.iloc[1:3,:-1]

,title,rating,ratingdescription,rating_level,release_year,user_rating_score
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0

## Handling missing values

In [24]:
data

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
...,...,...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

In [25]:
data.isnull().sum()

title                  0
rating                 0
ratingdescription     59
rating_level           0
release_year           0
user_rating_score    395
user_rating_size       0
dtype: int64

In [26]:
data["user_rating_score"].mean()

84.09421487603306

In [27]:
int(data["user_rating_score"].mean())

84

In [28]:
# Replace NaN with the mean of each column
#df.fillna(df.mean(), inplace=True)

In [29]:
data.replace(to_replace=np.nan, value=84,inplace=True)

In [30]:
data

,title,rating,ratingdescription,rating_level,release_year,user_rating_score,user_rating_size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,84.0,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
...,...,...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,84.0,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,84.0,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,84.0,82
999,Growing Up Wild,G,84,35,2016,80.0,80

In [ ]:
datad.to_csv('file1.csv')